# Generated by Django 5.0.2 on 2024-03-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_views_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotact',
            new_name='Contact',
        ),
    ]
