# Generated by Django 5.0.2 on 2024-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
